### ISSUE TITLE
Reduce Precision of Fraction

### ISSUE THREAD

**Issue by MadsKirkFoged** [danm-de/Fractions#14]
I am looking into creating more math operations for this library however i am hitting a wall where if I do too many calculation on a  `Fraction` its 'size' gets too large and slows down the calculation.
Many of the math operations will have a fixed Precision so it doesn't make much sense if the `fraction` can grow forever.

ex.
1071283/28187739 (decimal: 0.0380052830771563 )

Reduce precision so the largest BigInt is 4 -->
107/2815 (decimal: 0.038010657 )

I have looked into creating a method that does this but I cant seem to find a good way.
Do you have an idea for this?

**Comment by danm-de** [comment]
I'm sorry, I can't help here. That would be a good question for the math community.

Am 21. Februar 2022 15:52:09 MEZ schrieb MadsKirkFoged ***@***.***>:

**Comment by MadsKirkFoged** [comment]
I found a way :)
