### ISSUE TITLE
Improved to ToDouble

### ISSUE THREAD

**Issue by hjrb** [danm-de/Fractions#16]
Hi, I have been fiddling around to see if and how your library could be extended to support the new INumber<T> interface in C# so that something like this will work Enumerable.Range(1,100).Select(x=>new Fraction(1,x*x)).Sum(); // doesn't wort today as Sum is NOT generic. The result was: implementing INumber<T> is pretty straight forward.
But I stumbled upon the issue that converting the result failed returning double.NaN.
I had a quick look into the code for the ToDouble conversion. I think this would give a better result - but also be slower:
     private static readonly int maxDoubleDigits = (int)Math.Floor(Math.Log10(double.MaxValue) + 1);
        private static readonly BigInteger maxDoubleAsBigInt = new BigInteger(double.MaxValue);

        public double ToDouble()
        {
            if (IsZero)
            {
                return 0;
            }
            // here result could already be larger as double.MaxValue - but then the result is double.NaN anyways...
           // this can be avoided by the calling code be first getting the full part of the fraction and then only consider the fractional part for double conversion
            var result = BigInteger.DivRem(_numerator, _denominator, out BigInteger remainder);
            // ToDo: is _denominator always positive?
            if (_denominator > maxDoubleAsBigInt )
            {
                // get the number of digits of the _denominator
                int digits = (int)Math.Floor(BigInteger.Log10(_denominator) + 1);
                // create a factor that will reduce the number of digits to what double can still handle
                BigInteger factor = BigInteger.Pow(10, digits - maxDoubleDigits + 1);
                // now divide remainder and _denominator by the same factor (which will cancel them out - algebraically speaking).
                // and then divide the "shortened" values 
                double fraction = (double)(remainder / factor);
                fraction /= (double)(_denominator / factor);
                return (double)result + fraction;
            }
            else
            {
                return (double)result + (((double)remainder) / ((double)_denominator));
            }
}

An alternative would be to add a function (BigInteger FullPart, double Fraction) ToDouble()....

Thanks for providing this great library!

**Comment by danm-de** [comment]
Apologies for the late reply. I've seen the issue but haven't had time to look into it yet. I hope I can find a few minutes next week.

**Comment by danm-de** [comment]
Started with https://github.com/danm-de/Fractions/tree/feature/implement-inumber-net7

**Comment by danm-de** [comment]
Oh my, again sorry for the long delay - I would close this issue - NaN is also required here: https://github.com/danm-de/Fractions/issues/26
