### ISSUE TITLE
[BUG] Reciprocal of a negative fraction has invalid state

### ISSUE THREAD

**Issue by lipchev** [danm-de/Fractions#27]
Consider the following scenario:
<!DOCTYPE html>
<HTML>
<body>

  | Name | Value | Type
-- | -- | -- | --
  | new Fraction(-1, 10).Reciprocal().ToDecimal() | -10 | decimal

</body>
</HTML>

<!DOCTYPE html>
<HTML>
<body>

  | Expression| Value | Type
-- | -- | -- | --
  | new Fraction(-1, 10).Reciprocal().IsEquivalentTo(new Fraction(-10)) | false | bool

</body>
</HTML>

Normally this should have been true for the `Equals` as well, but I think this illustrates the issue better.

This problem stems from the fact that the sign of the fraction is not handled here
```
    public static Fraction Reciprocal(Fraction fraction) =>
        new Fraction(fraction.Denominator, fraction.Numerator, fraction.State);
```
According to `GetReducedFraction` a Normalized fraction should have it's signs normalized:
```
            if (denominator.Sign == -1) {
                // Denominator must not be negative after normalization
                numerator = BigInteger.Negate(numerator);
                denominator = BigInteger.Negate(denominator);
            }
```

I'd be willing to create a PR, but I was hoping that we could merge my "cleanup" of the test project first, if you don't mind..

**Comment by danm-de** [comment]
Oh, thanks.

I didn't even think about that when I merged https://github.com/danm-de/Fractions/pull/21 :-)
