### ISSUE TITLE
Why (19/9) % (19/27) == 0 ?

### ISSUE THREAD

**Issue by OlegJakushkin** [danm-de/Fractions#4]
So google [says `(19/9) % (19/27)`](https://www.google.com/search?q=19%2F27+-+38%2F77&oq=19%2F27+-+38%2F77&aqs=chrome..69i57.5879j0j1&sourceid=chrome&ie=UTF-8) is `0.21019721019`.

Yet this code (from latest nuget version):
```
            var a = new Fraction(19, 9);
            var b = new Fraction(19, 27);

            var mod = a % b;
            if (mod == 0) {
                Console.WriteLine("Bug");
            }
```

Gives:
![image](https://user-images.githubusercontent.com/2915361/90604901-3845c880-e206-11ea-80fe-c211083de619.png)

**Comment by OlegJakushkin** [comment]
BTW in production the bug can make a nice smooth curve into this jiggle:
![image](https://user-images.githubusercontent.com/2915361/90605126-97a3d880-e206-11ea-8aae-6ee8ec6c0e8b.png)
=)

**Comment by slepmog** [comment]
`(19/9) / (19/27)` = `(57/27) / (19/27)` = `(57*27)/(27*19)` = `57/19` = `3`.

**Comment by OlegJakushkin** [comment]
Ueah - sorry my bad.
