### ISSUE TITLE
Fraction.Zero.ToString("m") throws

### ISSUE THREAD

**Issue by lukenuttall** [danm-de/Fractions#6]
Fraction.Zero.ToString("m") throws a divide by zero.

**Comment by danm-de** [comment]
Ops, thanks for reporting!

Am 18. Februar 2021 17:10:04 MEZ schrieb Luke Nuttall <notifications@github.com>:
>Fraction.Zero.ToString("m") throws a divide by zero.
>
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/danm-de/Fractions/issues/6

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
