### ISSUE TITLE
Improvement: Constructor that takes 2 decimals

### ISSUE THREAD

**Issue by MadsKirkFoged** [danm-de/Fractions#7]
First of all, thank you for this project it works really great!

I wish for a contractor that takes 2 decimals

ex 

`Fraction value = new Fraction(4, 0.0254);`
so it sets it to `40000 / 254`

I tried using
`Fraction value = Fraction.FromString("4/0.0254");`
but that ignores the dot and returns a false result

**Comment by danm-de** [comment]
Hi,

what do think about

```csharp
var value = new Fraction(4m) / new Fraction(0.0254m);
``` 
?

![image](https://user-images.githubusercontent.com/3825484/125452789-e10f3c7f-717d-4bbf-9729-bc5c50444bbf.png)

**Comment by MadsKirkFoged** [comment]
That will work too!

Thank you!
