### ISSUE TITLE
Fraction.TryParse no longer accepts a nullable value (v8)

### ISSUE THREAD

**Issue by lipchev** [danm-de/Fractions#76]
I think there is a regression (but I cannot find where the change occurred):

In v7 this used to work:

    public static bool TryParse(string? valueString, NumberStyles parseNumberStyles, IFormatProvider? formatProvider, out QuantityValue quantityValue)
    {
        if (Fraction.TryParse(valueString, parseNumberStyles, formatProvider, out Fraction fraction))
        {
            quantityValue = new QuantityValue(fraction);
            return true;
        }

        quantityValue = default;
        return false;
    }

> Error (active)	CS8604	Possible null reference argument for parameter 'value' in 'bool Fraction.TryParse(string value, NumberStyles numberStyles, IFormatProvider? formatProvider, out Fraction fraction)'.

**Comment by danm-de** [comment]
![image](https://github.com/danm-de/Fractions/assets/3825484/c150e2ef-c433-4975-b4eb-61b846fae52c)

**Comment by danm-de** [comment]
My fault, I forgot to add nullable-marker.

**Comment by danm-de** [comment]
I have also added the changelog entry for version 8.0.0 to the release notes so that the breaking changes are also visible in Visual Studio (NuGet package manager).

![image](https://github.com/danm-de/Fractions/assets/3825484/f2d8b628-2379-4aca-b0ba-54b93354e1dc)
