### ISSUE TITLE
incorrect to say decimal fraction 0.1 represented by .0011 repeating

### ISSUE THREAD

**Issue by ubhub** [danm-de/Fractions#8]
Here and elsewhere in Microsoft and Stackoverflow forums, the advice on approximating the rational number one-tenth can be approximated in binary notation by .'0011', that is .001100110011 and so on. But it should read as .0'0011' or  .0001100110011 and so on. I've checked this manually for the first 9 binary places to get 51/512ths, which is close enough for me to put my correction. The current wording approximates one-fifth, not one-tenth.

**Comment by danm-de** [comment]
Hi, 
You are right. Thanks for reporting. 

<img src="https://render.githubusercontent.com/render/math?math=0.0011_b+%3D+0+%2A+2%5E%7B-1%7D+%2B+0+%2A+2%5E%7B-2%7D+%2B+1+%2A+2%5E%7B-3%7D+%2B+1%2A2%5E%7B-4%7D+%3D+0.1875">

<img src="https://render.githubusercontent.com/render/math?math=0.00011_b+%3D+0+%2A+2%5E%7B-1%7D+%2B+0+%2A+2%5E%7B-2%7D+%2B+0+%2A+2%5E%7B-3%7D+%2B+1%2A2%5E%7B-4%7D+%2B+1%2A2%5E%7B-5%7D+%3D+0.09375">
