### ISSUE TITLE
Update target frameworks

### ISSUE THREAD

**Issue by Bliamoh** [danm-de/Fractions#9]
Currently, supported target frameworks are:

``` xml
<TargetFrameworks>netstandard1.1;netstandard2.0;netstandard2.1;net45;net48;net5.0;netcoreapp3.1</TargetFrameworks>
```

However, these list of frameworks have two issues:

1. .NET Standard versions (1.1, 2.0, 2.1) already cover specific versions (like .NET 4.5), meaning it's an unecessary duplication. 
2. Some of them (.NET Standard 1.1 and .NET Framework 4.5) cover unsupported versions.

Here are some references to understand what I am talking about:

- Link of the [.NET implementation list](https://docs.microsoft.com/en-us/dotnet/standard/net-standard?WT.mc_id=dotnet-35129-website#net-implementation-support)
- Link of the [dynamic table of versions covered by .NET Standard](https://dotnet.microsoft.com/platform/dotnet-standard)
- Link of the [supported version of .NET Framework](https://dotnet.microsoft.com/download/dotnet-framework)

### Unecessary duplications

As you can see in the dynamic table of versions covered by .NET Standard:

- .NET Framework 4.5 is already covered by .NET Standard 1.1
- .NET Framework 4.8 is already covered by .NET Standard 1.1, 2.0 and 2.1
- .NET Core 3.1 is already covered by .NET Standard 1.1, 2.0 and 2.1
- .NET 5.0 is already covered by .NET Standard 1.1, 2.0 and 2.1

So you could simplify it like this:

``` xml
<TargetFrameworks>netstandard1.1;netstandard2.0;netstandard2.1</TargetFrameworks>
```

### Unsupported versions

The main question about this point is to know if why there is a direct reference to .NET Framework 4.5? 
Because .NET Framework 4.5 is not supported anymore since January 12, 2016. Furthermore, even if .NET Framework 4.5.2 is still supported, its support will end on April 26, 2022 so it could be a good idea to anticipate and change this now.
Moreover, .NET Framework 4.5.2, 4.6 and 4.6.1 versions support will end on April 26, 2022 so, as you can see in the dynamic table of versions covered by .NET Standard, .NET Standard 1.1 will soon become useless. So, the final version of targeted frameworks should be: 

``` xml
<TargetFrameworks>netstandard2.0;netstandard2.1</TargetFrameworks>
```

I am raising this issue because I am using your librairy and if its covering unsupported framework versions, then it may lead to security issues that my clients are concerned about.
So I would be glad to open a PR to fix that and do whatever is necessary for you to release a new version with these modifications.

**Comment by danm-de** [comment]
Thanks for the PR!
